"""Skill schema — Pydantic models for skills.

Single model: Skill is used for LLM structured output, internal storage,
rendering to SKILL.md, and parsing from SKILL.md. One model = round-trip
consistency guaranteed.

Bidirectional: Skill ↔ SKILL.md via renderer (to md) and parser (from md).
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any, Literal

from pydantic import BaseModel, Field

# ── Sub-models ───────────────────────────────────────────


class SkillRequires(BaseModel):
    """Dependencies the skill needs."""

    bins: list[str] = Field(default_factory=list, description="CLI binaries required")
    env: list[str] = Field(default_factory=list, description="Environment variables required")


class SkillParameter(BaseModel):
    """A variable input to the skill."""

    name: str = Field(description="Parameter name (snake_case)")
    description: str = Field(description="What this parameter controls")
    required: bool = Field(default=True)
    default: str = Field(default="", description="Default value if optional")
    constraints: str = Field(
        default="",
        description="Validation rule, e.g. 'valid room name' or 'positive integer'",
    )


class SkillScript(BaseModel):
    """A script file to bundle with or reference from the skill.

    Two modes:
    - Create: content is non-empty → saved to scripts/ directory.
    - Refer: content is empty, filename is an absolute path to an existing script.
    """

    filename: str = Field(
        description=(
            "For created scripts: bare filename (e.g. 'check_disk.py'). "
            "For existing scripts: absolute path (e.g. '/opt/tools/check_disk.py')."
        ),
    )
    content: str = Field(
        default="",
        description="Full script content including shebang. Empty when referencing an existing file.",
    )
    description: str = Field(
        default="",
        description=(
            "What this script does. For referenced external scripts, also "
            "describe how to invoke it (args, expected output)."
        ),
    )


# ── Verification ─────────────────────────────────────────


class VerifyCondition(BaseModel):
    """How to verify a step succeeded.

    Generated by the LLM at skill creation time. The StepVerifier
    tries the stated strategy first, then falls back through
    AX → text → visual if the primary strategy fails (hybrid 1C).
    """

    strategy: Literal["ax_element", "visual", "text_content"] = Field(
        description="Primary verification strategy",
    )
    # For ax_element strategy:
    ax_role: str = Field(
        default="",
        description="Expected AX role (e.g., 'AXButton', 'AXSheet')",
    )
    ax_title: str = Field(
        default="",
        description="Expected element title or label",
    )
    # For text_content strategy:
    expected_text: str = Field(
        default="",
        description="Text that should appear on screen",
    )
    # For visual strategy (LLM-based):
    description: str = Field(
        default="",
        description="Human-readable verification text: what the screen should "
        "look like after this step. Also used as fallback for visual strategy.",
    )


class StepFigure(BaseModel):
    """A figure reference with a descriptive caption."""

    ref: str = Field(
        description=(
            "Frame reference: 'overview_N' or 'detail_N' where N is the "
            "Frame number from the timeline. Only reference images declared "
            "in that frame's header."
        )
    )
    caption: str = Field(
        description=(
            "Short descriptive caption explaining what this figure shows, "
            "e.g. 'GlobalProtect VPN connected state' or 'df -Th output showing disk usage'."
        )
    )


# ── Branching ─────────────────────────────────────────────


class Branch(BaseModel):
    """A conditional edge in the step DAG.

    Default flow: steps execute in list order (implicit next).
    Branches override the default by jumping to a named step when
    the condition is met. Multiple branches from different steps
    can target the same next_step — this is how paths converge.
    """

    condition: VerifyCondition = Field(
        description="Condition to check; uses the same verification "
        "strategies as step verification (AX, text, visual)",
    )
    next_step: str = Field(
        description="Name of the step to jump to (references Step.name)"
    )


# ── Step model ────────────────────────────────────────────


class Step(BaseModel):
    """A single step in the skill workflow.

    A step has name + action. Name is a short kebab-case identifier
    that doubles as the heading and branch target. Action describes
    how to perform the step.
    """

    name: str = Field(
        description="Short kebab-case identifier: what this step achieves. "
        "Used as heading and branch target (e.g. 'open-export-dialog').",
    )
    action: str = Field(
        description=(
            "How to do it — human-readable description using app names, "
            "UI labels, and parameters."
        )
    )
    target_app: str = Field(
        default="",
        description=(
            "Target application for this step (e.g., 'TextEdit', 'Finder'). "
            "Used by the verifier to query the correct accessibility tree."
        ),
    )
    tool: str = Field(
        default="",
        description=(
            "Optional Protean MCP tool string, such as a single tool, "
            "short tool chain, or run_terminal_command(command='...')."
        ),
    )
    verify_condition: VerifyCondition | None = Field(
        default=None,
        description="Structured verification condition. Used by StepVerifier.",
    )
    figures: list[StepFigure] = Field(
        default_factory=list,
        description=(
            "Figures illustrating this step. Each has a ref (frame label from "
            "the evidence, e.g. 'overview_3') and a caption describing what it shows."
        ),
    )
    branches: list[Branch] = Field(
        default_factory=list,
        description=(
            "Conditional edges in the step DAG. Each branch jumps to a "
            "named step when its condition is met, overriding the default "
            "sequential flow."
        ),
    )
    idempotent: bool = Field(
        default=True,
        description=(
            "Whether this step is safe to retry on failure. "
            "False for irreversible actions like sending email or submitting forms."
        ),
    )


# ── Skill model ──────────────────────────────────────────


class Skill(BaseModel):
    """The skill model. Used everywhere:

    - LLM structured output (fields LLM doesn't fill get defaults)
    - Internal storage and editing
    - Rendering to SKILL.md
    - Parsing from SKILL.md
    """

    name: str = Field(description="Kebab-case skill name, max 5 words")
    description: str = Field(
        description="One-line: what this skill does and when to use it. "
        "This is what the agent reads to decide whether to invoke this skill."
    )

    when_to_use: list[str] = Field(
        default_factory=list,
        description="Trigger phrases — when the agent should use this skill",
    )
    when_not_to_use: list[str] = Field(
        default_factory=list,
        description="Anti-patterns — when this skill is NOT appropriate",
    )

    goal: str = Field(default="", description="Overall goal in one sentence")
    steps: list[Step] = Field(default_factory=list, description="Ordered workflow steps")
    success_criteria: list[str] = Field(
        default_factory=list,
        description="How to know the entire task succeeded",
    )

    requires: SkillRequires = Field(default_factory=SkillRequires)
    install: list[str] = Field(
        default_factory=list,
        description="Install commands, e.g. 'brew install gh'",
    )
    parameters: list[SkillParameter] = Field(default_factory=list)
    scripts: list[SkillScript] = Field(default_factory=list)
    tags: list[str] = Field(default_factory=list)

    # Fields not filled by LLM — excluded from JSON schema for structured output
    source: str = Field(default="", json_schema_extra={"exclude_from_llm": True})
    related_skills: list[str] = Field(
        default_factory=list,
        description="Names of skills that compose with or relate to this one",
        json_schema_extra={"exclude_from_llm": True},
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        json_schema_extra={"exclude_from_llm": True},
    )

    # Transient: image bytes for figures, populated during generation, written by renderer
    figure_data: dict[str, bytes] = Field(
        default_factory=dict,
        exclude=True,
        json_schema_extra={"exclude_from_llm": True},
    )

    # Backward compat: flat instructions from old-format skills (no structured steps)
    instructions: str = Field(default="", json_schema_extra={"exclude_from_llm": True})

    def normalize_name(self) -> None:
        """Normalize name to strict kebab-case in place."""
        self.name = re.sub(r"[^a-z0-9-]", "-", self.name.lower().strip())
        self.name = re.sub(r"-+", "-", self.name).strip("-")

    def validate_steps(self) -> list[str]:
        """Check step name uniqueness and branch target resolution.

        Returns a list of error messages (empty = valid).
        """
        errors: list[str] = []
        names: dict[str, int] = {}
        for i, step in enumerate(self.steps):
            if not step.name:
                errors.append(f"Step {i}: missing name")
                continue
            if step.name in names:
                errors.append(
                    f"Step {i} ({step.name!r}): duplicate name "
                    f"(first at step {names[step.name]})"
                )
            names[step.name] = i

        # Check branch targets resolve
        for i, step in enumerate(self.steps):
            for br in step.branches:
                if br.next_step not in names:
                    errors.append(
                        f"Step {i} ({step.name!r}): branch target "
                        f"{br.next_step!r} does not match any step name"
                    )
        return errors

    def validate_scripts(self) -> list[str]:
        """Check SkillScript entries are mode-consistent.

        Returns a list of error messages (empty = valid).

        Rules (from SkillScript docstring):
          * Create mode (content non-empty): filename must be a bare basename
            (no path separators). LLMs sometimes emit container paths like
            '/root/.codex/skills/.../foo.py' which would otherwise escape the
            scripts/ directory when joined.
          * Refer mode (content empty): filename must be an absolute path.
            The path is interpreted in the agent's runtime environment
            (typically inside a container), so we can't check existence
            from here — but a bare filename with no content is always a
            phantom and is rejected.
        """
        errors: list[str] = []
        for i, s in enumerate(self.scripts):
            if s.content:
                if Path(s.filename).name != s.filename:
                    errors.append(
                        f"Script {i} ({s.filename!r}): create-mode "
                        f"(content non-empty) requires a bare filename, "
                        f"got a path"
                    )
            else:
                p = Path(s.filename)
                if not p.is_absolute():
                    errors.append(
                        f"Script {i} ({s.filename!r}): refer-mode "
                        f"(content empty) requires an absolute path to an "
                        f"existing script in the agent's environment; got a "
                        f"non-absolute path with no content (phantom "
                        f"reference). If you intend to bundle a new script, "
                        f"set 'content' to the script body."
                    )
        return errors

    def save(self, output_dir: Path) -> Path:
        """Render this skill to SKILL.md + scripts/ on disk."""
        from protean.skills.renderer import render_skill

        return render_skill(self, output_dir)


def to_kebab(text: str, max_words: int = 5) -> str:
    """Convert free text to kebab-case, max N words."""
    words = re.sub(r"[^a-z0-9]+", " ", text.lower()).split()[:max_words]
    return "-".join(words) or "step"
